services:
  db:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: gestion_salaries
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root1234
    ports:
      - "33060:3306" # using port 33060 to avoid conflict with local MySQL
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build: ./gestion-salaries-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/gestion_salaries?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: app
    ports:
      - "8081:8080"

  web:
    build: ./gestion-salaries-frontend
    ports:
      - "8082:80"
    depends_on:
      - api

volumes:
  db_data: